spring:
  application:
    name: resired
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: 'true'
        jdbc:
          batch_size: '100'
        order_updates: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /api
